version: '3.4'
x-common-variables: &common-variables
  # For db connection in ECS
  DB_USERNAME: ${RY_RDS_USERNAME}
  DB_PASSWORD: ${RY_RDS_PASSWORD}
  DB_HOST: ${RY_RDS_HOST}
  # # For db connection locally
  # DB_USERNAME: ${DB_USERNAME}
  # DB_PASSWORD: ${DB_PASSWORD}
  # DB_HOST: ${DB_HOST}
  # Vars that don't need to be the changed
  DB_PORT: ${RY_DB_PORT}
  DB_NAME: ${RY_DB_NAME}
  ENCRYPT_SECRET_KEY: ${RY_ENCRYPT_SECRET_KEY}
  JWT_SECRET_KEY: ${RY_JWT_SECRET_KEY}

services:
  # gateway:
  #   image: noodleween/aline-gateway-ry:corretto
  #   ports:
  #     - ${GATEWAY_M}
  #   environment:
  #     APP_PORT: ${GATEWAY_M}
  #     # APP_SERVICE_HOST: ${APP_SERVICE_HOST}
  #     APP_SERVICE_HOST: host.docker.internal:host-gateway
  #   # network_mode: bridge
  #   # extra_hosts:
  #   #   - "host.docker.internal:host-gateway"

  user:
    image: noodleween/aline-user-ry:corretto
    # # for local use only
    # depends_on:
    #   - db
    ports:
      - ${RY_USER_M}:${RY_USER_M}
    environment:
      <<: *common-variables
      APP_PORT: ${RY_USER_M}

  # underwriter:
  #   image: noodleween/aline-underwriter-ry:corretto
  #   # # for local use only
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - ${UNDERWRITER_M}
  #   environment:
  #     <<: *common-variables
  #     APP_PORT: ${UNDERWRITER_M}

  # account:
  #   image: noodleween/aline-account-ry:corretto
  #   # # for local use only
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - ${ACCOUNT_M}
  #   environment:
  #     <<: *common-variables
  #     APP_PORT: ${ACCOUNT_M}

  # transaction:
  #   image: noodleween/aline-transaction-ry:corretto
  #   # # for local use only
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - ${TRANSACTION_M}
  #   environment:
  #     <<: *common-variables
  #     APP_PORT: ${TRANSACTION_M}

  # bank:
  #   image: noodleween/aline-bank-ry:corretto
  #   # # for local use only
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - ${BANK_M}
  #   environment:
  #     <<: *common-variables
  #     APP_PORT: ${BANK_M}

# # This is a database for running compose locally
#   db:
#     image: 'mysql:latest'
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_PASSWORD: Password
#       MYSQL_USER: admin
#       MYSQL_DATABASE: alinedb
#     volumes:
#       - db-data:/var/lib/mysql
#     ports:
#       - 13306:3306

# volumes:
#   db-data:
#     driver: 'local'
