version: '3.4'
x-common-variables: &common-variables
  # For db connection in ECS
  DB_USERNAME: ${RDS_USERNAME}
  DB_PASSWORD: ${RDS_PASSWORD}
  DB_HOST: ${RDS_HOST}
  # # For db connection locally
  # DB_USERNAME: ${DB_USERNAME}
  # DB_PASSWORD: ${DB_PASSWORD}
  # DB_HOST: ${DB_HOST}
  # Vars that don't need to be the changed
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}

x-aws-loadbalancer: "arn:aws:elasticloadbalancing:us-east-1:541351699142:loadbalancer/net/alineLoadBalancer/7aa577f2fa563b65"

services:
  gateway:
    image: noodleween/aline-gateway-ry:corretto
    build: aline-gateway-RY
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: 1GB
    ports:
      - ${GATEWAY_M}
    environment:
      APP_PORT: ${GATEWAY_M}
      # APP_SERVICE_HOST: ${APP_SERVICE_HOST}
      APP_SERVICE_HOST: alineLoadBalancer-7aa577f2fa563b65.elb.us-east-1.amazonaws.com
    # network_mode: bridge
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  user:
    image: noodleween/aline-user-ry:corretto
    build: aline-user-microservice-RY
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: 1GB
    # # for local use only
    # depends_on:
    #   - db
    ports:
      - ${USER_M}:${USER_M}
    environment:
      <<: *common-variables
      APP_PORT: ${USER_M}

  underwriter:
    image: noodleween/aline-underwriter-ry:corretto
    build: aline-underwriter-mircoservice-RY
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: 1GB
    # # for local use only
    # depends_on:
    #   - db
    ports:
      - ${UNDERWRITER_M}
    environment:
      <<: *common-variables
      APP_PORT: ${UNDERWRITER_M}

  account:
    image: noodleween/aline-account-ry:corretto
    build: aline-account-microservice-RY
    # # for local use only
    # depends_on:
    #   - db
    ports:
      - ${ACCOUNT_M}
    environment:
      <<: *common-variables
      APP_PORT: ${ACCOUNT_M}

  transaction:
    image: noodleween/aline-transaction-ry:corretto
    build: aline-transaction-microservice-RY
    # # for local use only
    # depends_on:
    #   - db
    ports:
      - ${TRANSACTION_M}
    environment:
      <<: *common-variables
      APP_PORT: ${TRANSACTION_M}

  bank:
    image: noodleween/aline-bank-ry:corretto
    build: aline-bank-microservice-RY
    # # for local use only
    # depends_on:
    #   - db
    ports:
      - ${BANK_M}
    environment:
      <<: *common-variables
      APP_PORT: ${BANK_M}

# # This is a database for running compose locally
#   db:
#     image: 'mysql:latest'
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_PASSWORD: Password
#       MYSQL_USER: admin
#       MYSQL_DATABASE: alinedb
#     volumes:
#       - db-data:/var/lib/mysql
#     ports:
#       - 13306:3306

# volumes:
#   db-data:
#     driver: 'local'
